apiVersion: v1
kind: ReplicationController
metadata: 
      name: todoreplica
      labels: 
          app: todoreplica
spec: 
  replicas: 2
  template: 
        metadata: 
            name: todoreplica
            labels:
              app: todoreplica
        spec: 
          containers: 
            - name: todo
              image: fazilasayyed/todo
              resources: 
                requests:
                  cpu: "50m"
                  memory: "90Mi" 
              ports:  
                - containerPort: 80
                  protocol: TCP 
  selector:
      app: todoreplica
